### ISSUE TITLE
Print in main prints twice

### ISSUE THREAD

**Issue by lemonad** [marcusz/floyd#7]
Not sure if this is a bug or not but, as a user, I think it is unexpected behaviour. Running the program

```
func int main ([string] args) impure {
  print(5)
  return 0
}

main([])
```

gives the result

```
❯ ../FloydLang/floyd/floyd run ./test.floyd
5
5
```

**Comment by marcusz** [comment]
Yes, that's wrong. Will fix.

**Comment by marcusz** [comment]
No, that's correct. main() is always called automatically by the runtime, after all your global statements have executed. Remove the main([]) call and you will be fine.

**Comment by marcusz** [comment]
Close this issue if you agree.

**Comment by lemonad** [comment]
Aha, that's why the examples used `test_main`. My bad -- closing this. Thanks for the heads up!
