### ISSUE TITLE
How do I pass function arguments to reduce, map, etc?

### ISSUE THREAD

**Issue by kaislavirta** [marcusz/floyd#74]
When I try to use reduce() on a vector as per example, I get "reduce() requires 3 arguments"

```
func int addNumbersInJson(int acc, json_value json) {
	let type = get_json_type(json)

	if(type == json_object) {

	}
	else if(type == json_array) {
		return reduce(json, acc, addNumbersInJson)
	}
	else if(type == json_number) {
		return jsonvalue_to_value(json, int)
	}
	else {
		// Ignore
	}
}
```

How should I call it?

**Comment by marcusz** [comment]
Reduce works like this: R reduce([E], R init, R f(R accumulator, E element))

Argument 1: the vector with elements of type E
Argument 2: an initial value of the same type you want the final result to be.
Argument 3: a function that take the current accumulator value (type R), one of the elements (type E) and returns a new result R.

Documentation needs more information. There are some examples in floyd_test_suite.cpp:

```
func int f(int acc, int element){
	return acc + element * 2
}

let result = reduce([ 10, 11, 12 ], 2000, f)

print(to_string(result))
assert(result == 2066)
```

and 

```
func string f(string acc, int v){
	mutable s = acc
	for(e in 0 ..< v){
		s = "<" + s + ">"
	}
	s = "(" + s + ")"
	return s
}

let result = reduce([ 2, 4, 1 ], "O", f)
print(to_string(result))
assert(result == "(<(<<<<(<<O>>)>>>>)>)")
```

**Comment by kaislavirta** [comment]
I realized my bad was probably that the function argument was a jason_value. Would be cool if those could be used in map functions as well, somehow :)

**Comment by marcusz** [comment]
Closing this issue
