### ISSUE TITLE
Does floyd compile in floyd?

### ISSUE THREAD

**Issue by tilkinsc** [marcusz/floyd#77]

**Comment by marcusz** [comment]
Hi Cody!

No, the Floyd compiler and tools are written in C++17. I'm not planning to rewrite these using Floyd. It would be an interesting experiment at some point.

**Comment by tilkinsc** [comment]
Do you want me to leave this open?

**Comment by marcusz** [comment]
Dunno, I'm not used to collaborating via github. What do you think is best? It's a reasonable question and definitely helpful for other people in the future.

**Comment by tilkinsc** [comment]
Future people can search it and are likely to see it is open. So I guess it's best to leave it open. Someone might contribute.

**Comment by marcusz** [comment]
I'm closing this for now.
