### ISSUE TITLE
Invalid range syntax causes correct error message but points to line in corelib

### ISSUE THREAD

**Issue by lemonad** [marcusz/floyd#8]
I accidentally used the wrong range construct in a for loop

```
for (i in 1..5) {
  print(i)
}
```

and got the following error message

```
For loop has illegal range syntax. Line: 2 "let double cmath_pi = 3.14159265358979323846" file: corelib
```

**Comment by marcusz** [comment]
Can reproduce.

**Comment by marcusz** [comment]
Have made a new branch, master-fixes, that reproduces this problem (the test is disabled for now).

**Comment by marcusz** [comment]
New, correct error will be: For loop has illegal range syntax. Line: 1 "for (i in 1..5) {"

**Comment by marcusz** [comment]
This fix is in master, please verify and close.

**Comment by lemonad** [comment]
Verified as working. Thanks!
